# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev/envoy-build-script

# pool:
#   vmImage: ubuntu-20.04

# steps:

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

jobs:
- job: envoy_build
  timeoutInMinutes: 400
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
      dockerVersion: 17.09.0-ce
      releaseType: stable
  - script: |
      cd envoy-filters/envoy
      git submodule update --init
      git checkout v1.16.0
      cd ..  
      cd envoy-filters
      ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'
    displayName: 'envoy build' 